apiVersion: v1
kind: ResourceQuota
metadata:
  name: nodejs-app-quota
  namespace: nodejs-app-namespace
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "700Mi"
    limits.cpu: "1000m"
    limits.memory: "1.5Gi"
    pods: "10"
    services: "5"